---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-storming
  labels:
    app: event-storming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-storming
  template:
    metadata:
      labels:
        app: event-storming
    spec:
      containers:
        - name: event-storming
          image: username/event-storming:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn
  labels:
    app: bpmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn
  template:
    metadata:
      labels:
        app: bpmn
    spec:
      containers:
        - name: bpmn
          image: username/bpmn:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: event-storming
  labels:
    app: event-storming
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: event-storming


---


apiVersion: v1
kind: Service
metadata:
  name: bpmn
  labels:
    app: bpmn
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bpmn

